apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
  namespace: traefik-2-1
  labels:
    app: traefik-ingress-service
spec:
  type: NodePort
  selector:
    app: traefik-ingress-lb
  ports:
  - name: web
    port: 80
    targetPort: web
    protocol: TCP
  - name: websecure
    port: 443
    targetPort: websecure
    protocol: TCP